# See http://www.appveyor.com/docs/appveyor-yml for many more options

branches:
  only:
    - solutions
    - development

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*/

build: false

install:
  - cinst pester


test_script:
# Test with native PS version
  - ps: . .\src\appveyor.pester.ps1
# Test with PS version 2
  - ps: powershell.exe -version 2.0 -executionpolicy bypass -noprofile -file .\src\appveyor.pester.ps1
# Finalize pass - collect and upload results
  - ps: . .\src\appveyor.pester.ps1 -Finalize
